plate_management: &plate_management_settings
  well_type: "Well"
  plate_type: "Plate"
  gel_type: "GelDilutionPlate"
  asset_type: "Asset"
  sample_type: "Sample"
  roles_purpose_ids:
    "samples.rack.stock.dna": 2
    "samples.rack.stock.rna": 183
    "samples.qc.nx_nanodrop.working_dilution_rna": 1
    "samples.qc.nx_nanodrop.working_dilution_rna.nanodrop": 1
    "samples.qc.nx_nanodrop.volume_checked_stock_rack_rna.batched": 183
    "samples.qc.nx_nanodrop.volume_checked_stock_rack_rna": 183
  unassigned_plate_purpose_id: 2
  item_role_patterns:
    - "stock"
    - "working_dilution"
  item_done_status: "done"
  sanger_barcode_type: "sanger-barcode"
  plate_location: "Sample logistics freezer"
  create_asset_request_sti_type: "CreateAssetRequest"
  create_asset_request_type_id: 11
  create_asset_request_state: "passed"
  transfer_request_sti_type: "TransferRequest"
  transfer_request_type_id: 22
  transfer_request_state: "passed"
  out_of_bounds_concentration_key: "Concentration"
  stock_plate_concentration_multiplier: 12.5
  barcode_prefixes: 
    "ND": "Plate"
    "NR": "Plate"
    "WD": "Working dilution"
    "WR": "Working dilution"
  gel_image_s2_scores_to_sequencescape_scores:
    "pass": "OK"
    "fail": "fail"
    "degraded": "Degraded"
    "partially degraded": "Partially degraded"

sample_management: &sample_management_settings
  sample_type: "Sample"
  study_sample_type: "StudySample"

default: &default
  plate_management:
    <<: *plate_management_settings
  sample_management:
    <<: *sample_management_settings

